### PR TITLE
Support Echo Show directive

### PR DESCRIPTION
**Pull request by Jasc01**
## Echo Show Directive

Added a new folder into the UI with the necessary files for the Echo Show directive. These includes all the possible basic options the user can change:

- Tittle
- Background Image
- Main Image
- Primary Text Content
- Secondary Text Content
- Tertiary Text Content

Also, the user can change the properties available for the text content and the format of the UI in general:

- Type of text (plain or rich text)
- Type of template
- Back button

Here is a screenshot of how the directive will be sent to the Amazon Alexa service:

capture

### Notes

- There's still no support for the "List Items" option, but it is planned for the near future to support it.
- The way you need to set up every value in the directive is very inconvenient and ugly, but I believe this can be resolved by each person that implements the library since there are a lot of ways to fix it, and everyone can come up with a different solution depending on whatever they need to do.

### Reference

If you need to know more about what an Echo Show directive is and what it can do, [here's](https://developer.amazon.com/docs/custom-skills/display-interface-reference.html) the official link where we got all the information we needed to make the directive.

---
Even though the commits are only mine, the changes were made by [Aifos29](https://github.com/aifos29) and [me](https://github.com/Jasc01)

### CODE REVIEW

**Comment by psantiago1969** [comment]
Any plans to update code again?  Looking for Display_ElementSelected and the List templates?  I am playing around trying to make something work to share as well.
Cheers

**Comment by stefann42** [comment]
@Jasc01 This is a great PR, thanks! How much testing have you done? One reason I'm slow about merging PRs is that I feel I need to test everything myself before releasing. If you can help me get assurance about QA I'd love to get this into the main library asap.

**Comment by stefann42** [comment]
@psantiago1969 Sorry for being slow. I'm swamped with other priorities at my work and need some help managing this project. As soon as I can test/validate this PR happy to merge and release. As for new features I'm afraid it's not a priority for me, but might be for @Jasc01

**Comment by petersantiago** [comment]
I have used the code Jasc01 provided and it works great.  However, I am working on Display_ElementSelected for BodyTemplates  and the List templates usage.

**Comment by teriansilva** [comment]
If you want to play a video with this on echo show, its currently not working. For that to work, you need to make the ShouldEndSession property nullable.

**Comment by Jasc01** [comment]
@stefann42 Sorry for my late reply. I have used this code for a few months now and there's not been problems with it. One thing I haven't done is to publish an skill using this code, so I can't prove that point yet (maybe in the future, but I don't really know).

 @psantiago1969 @petersantiago To use those features is not a priority in my projects, thus I'm not planning to make any of them in the near future. But it would be nice if you help us and provide the necessary code for it. Actually, it would be really great! :smile: 

@teriansilva I'm sorry, but playing a video wasn't one of my requirements. However, you are free to make the necessary changes for it to work, of course. :smiley: :+1:

**Pull request merged**
