### PR TITLE
Audio Directive Support

### PR DESCRIPTION
**Pull request by dg-racing**
Added complete support for audio directives and it's accompanied required objects. It's not perfect and I'm open to feedback on what could be better but I also know how badly needed this support is. 

Thanks!

### CODE REVIEW

**Comment by stefann42** [comment]
Thanks for this contribution! I'll review and merge soon.

**Comment by dg-racing** [comment]
FYI, I've now got a skill certified and public at Amazon with this build.

**Comment by smussani** [comment]
Great!! Would it be possible to upload a sample project that shows how you are calling these directives?
What is the name of your skill? Can I enable it under my Echo to listen?

**Comment by dg-racing** [comment]
Sorry for the delayed response. Yes, it went live last week. The skill name is Church of The Highlands (Unofficial) and it is running my fork of this project. I never had any feedback from Amazon with regards to anything "framework related." Just a few standard bugs here and there.

**Comment by smussani** [comment]
Anyway you can put a sample project or give some code snippets on how to call Play, enqueue, pause intents using this code?
Thx

**Comment by dg-racing** [comment]
This should be enough to get you started.
```csharp
private CreateAudioResponse(string url, long? offset, string token)
{
            var response = new SpeechletResponse();
            var dir = new Directive
            {
                AudioItem = new AudioItem
                {
                    Stream = new AudioStream
                    {
                        Url = url,
                        Token = token ?? Convert.ToBase64String(Guid.NewGuid().ToByteArray())
                    }
                }
            };
            dir.Type = "AudioPlayer.Play";
            dir.PlayBehavior = "REPLACE_ALL";
            dir.AudioItem.Stream.OffsetInMilliseconds = offset.GetValueOrDefault(0);

            response.Directives = new List<Directive> { dir };

            response.ShouldEndSession = true;
            return response;
}

**Comment by smussani** [comment]
thanks.. will try it out.

**Comment by dg-racing** [comment]
Any word on this?

**Comment by stefann42** [comment]
@dg-racing Sorry for the delay and thanks again for you contribution! Please sign the Contributor License Agreement (see your pull request) so can we accept it in the project.

**Comment by dg-racing** [comment]
Sorry about the confusion earlier. I had a commit with a bad email address and had to roll it back. All should be good now for the pull request.

**Comment by dg-racing** [comment]
Any chance we can get this merged?

**Comment by dg-racing** [comment]
Bro. Merge? Please?

**Comment by dg-racing** [comment]
What's the deal here? This pull request has been sitting for 6 months waiting on a merge. Is this library not getting any updates any further? If not, can you turn it over to someone or some group that would be willing to continue maintaining it? This is really frustrating.

**Comment by dg-racing** [comment]
Can you resolve the merge conflicts and get this guy merged?

**Comment by kienct89** [comment]
hi all, any plan to merge this PR?

**Comment by genetipetz** [comment]
@stefann42 Please merge this and bump a new version.  The audio capability is vital to well-rounded skills and your library is the gold standard so many of depend upon.  Thank you!

**Comment by ElvenMonky** [comment]
@stefann42 I can merge this PR together with #49, #52 and #53 to provide consolidated version. Will it work for you?

**Comment by stefann42** [comment]
@ElvenMonky Yes, please.

**Pull request merged**
