### PR TITLE
Add Directives support in SpeechletResponse

### PR DESCRIPTION
**Pull request by ElvenMonky**
I've added Directive types for all directive currently described in the documentation. Have tested only Dialog Directives with my skill though.

### CODE REVIEW

**Comment by ElvenMonky** [comment]
I've also reviewed implementation of directives in original Java library. They doesn't seem to provide implementation to directives other than [https://github.com/amzn/alexa-skills-kit-java/tree/master/src/com/amazon/speech/speechlet/dialog/directives](Dialog directives). As for Dialog directives, it looks like they added to new types: DialogIntent and DialogSlot, with the only difference from Intent and Slot in missing Slot.Resolutions field. However, documentation directly states that updatedIntent field takes an Intent object (https://developer.amazon.com/docs/custom-skills/dialog-interface-reference.html#use-updatedintent). And new added types don't enforce restriction of not changing intent and slot names, so I don't think we should do this as well.

**Comment by ElvenMonky** [comment]
@stefann42, @dg-racing, @Jasc01, @teriansilva : I've merged #23, #48 (only locale support), #52 (with #49) into this PR. I consider this a minimal required update. #41 is covered by these changes. #31 mostly interferes, but contains basic permissions support, so has to be merged separately.
Could you, please, review changes and leave your comments?

**Comment by stefann42** [comment]
@ElvenMonky You rock! Thanks for the quick turnaround. To clarify, rather than code review and merge https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/pull/23, https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/pull/48, https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/pull/52, https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/pull/49, https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/pull/41, and https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/pull/31 I should code review this PR (https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/pull/53) and merge, correct?

**Comment by ElvenMonky** [comment]
Yes, exactly.

**Comment by ElvenMonky** [comment]
Sorry for inconvinience, but I found it necessary to provide better support for all current request types. So I've added one more commit to PR.
Hovever, more interfaces with new directives and requests can be added in the future, so we need to find a way to make Speechlet extensible by external interface libraries, and probably extract existing interfaces into separate assemblies (and nuget packages), as not all skills will use all available interfaces.

**Pull request merged**
